### ISSUE TITLE
Not installing 

### ISSUE THREAD

**Issue by vulfox** [dnbard/brackets-extension-rating#100]
Just installed Brackets and tried to install Extensions Rating through extension manager in brackets. Clicked install, the install starts and then:

"Installation failed."
"The extension encountered an error while starting up."

Brackets version:
Release 1.1 build 1.1.0-15558 (release ea908cae5) 
OS X Mavericks

**Comment by dnbard** [comment]
This issue is related to Brackets Extensions service that is not managed by me.
Try to install extension later and if error still be there then create new issue in main Brackets repository.

Also I've tried to install this extension and installation was successful.

**Comment by vulfox** [comment]
If you say so. Though this only happens with this extension for me.
Still no luck installing.

**Comment by dnbard** [comment]
Alternatively, you can unzip [extension](https://s3.amazonaws.com/extend.brackets/dnbard.extensions-rating/dnbard.extensions-rating-0.6.0.zip) to /Brackets/Extensions/User/ExtensionRating
