### ISSUE TITLE
Extension Error (Promise defer)

### ISSUE THREAD

**Issue by Hirse** [dnbard/brackets-extension-rating#101]
I have used your extension for some time and really like it, but since I came back from holiday earlier this week, it doesn't work any more. I get this error message which seems to be connected to a thirdparty module that you are using.
It might be connected to the Brackets 1.1 Update because that is the only thing I changed after being back.
![bug_extension_rating](https://cloud.githubusercontent.com/assets/2564094/5660021/5788a244-971b-11e4-81ca-5e426e6b2cff.PNG)

**Comment by dnbard** [comment]
@Hirse I can't reproduce this issue and I don't think that it is related to Brackets 1.1 update. I think that some extension corrupted your Brackets environment. This happen a lot in the past with the same error. Try to locate which extension doing it.

**Comment by Hirse** [comment]
You are right, the issue is only present while I have the CSSLint extension installed.
I have submitted an [issue there](https://github.com/cfjedimaster/brackets-csslint/issues/35).
Thanks for your quick response.
