### ISSUE TITLE
Website Top 100 

### ISSUE THREAD

**Issue by Wikunia** [dnbard/brackets-extension-rating#102]
Hi Alex,
At the moment you only show random extensions that are in the top 100. I think it would be awesome to see all of them and maybe sort by stars, total downloads and downloads for the latest version :)
Thanks!

**Comment by dnbard** [comment]
Yeah! I thought about this before. Will try to find time for this (at least for first part).

**Comment by Wikunia** [comment]
Maybe you would like to add the rank information to the single sites, too ;)

**Comment by dnbard** [comment]
Done
