### ISSUE TITLE
strange download number for the top extension and weird info link

### ISSUE THREAD

**Issue by zaggino** [dnbard/brackets-extension-rating#107]
Are these numbers correct? 408056 downloads?
When I click `More info...` I'm being sent to some Russian website ...
![image](https://cloud.githubusercontent.com/assets/1067319/6260426/ac0cae0e-b832-11e4-8490-007221349a6b.png)

**Comment by dnbard** [comment]
This number is correct(it provided by Brackets Extensions Registry and not calculated by my service). But I think that the author of this extension did a most of downloads by himself using some script. This is what I have in my downloads database:

![2015-02-19_0956](https://cloud.githubusercontent.com/assets/4028472/6263289/b7ec6cd8-b81d-11e4-9e73-9aced39118cc.png)

So as you can see the most downloads (from 3500 to 404 500) were made during the 2 weeks. And there no such pattern with any other extension in my database.

Also his nickname in English will be "Newbie guy 2000" so I think he just a teenager who wanted to create the "best extension ever".

I've already exclude his extension from rating at [http://brackets.dnbard.com] (http://brackets.dnbard.com) and I will do the same inside Brackets (just wont show his download stats, extension will remain in registry and will be available to search and download).

**Comment by dnbard** [comment]
Fixed in previous release.
