### ISSUE TITLE
Regarding the typeface on http://brackets.dnbard.com/extensions

### ISSUE THREAD

**Issue by larz0** [dnbard/brackets-extension-rating#108]
Hi @dnbard, I really like http://brackets.dnbard.com/extensions 👍

I have a small issue with the typeface used on it and I'm not sure if it's just me; the fonts on that page is  a little hard for me to read on my setup (latest Safari on OS X Yosemite):

![screen shot 2015-02-18 at 4 59 09 pm](https://cloud.githubusercontent.com/assets/1495261/6260460/e1b7295c-b793-11e4-8ba7-2eb58fa4044d.png)

I wonder if we can change the typeface to Source Sans Pro like the Brackets app and brackets.io since you've already done a good job at making the rest of the page consistent with brackets.io.

Thanks!

**Comment by dnbard** [comment]
I though that I'm using the correct font. Thanks, I'll add *Source Sans Pro* as soon as possible. Is this font freely available?

**Comment by larz0** [comment]
This font is freely available as a web font by including:

 ```<script src="//use.edgefonts.net/source-sans-pro:n3,n4,n6,i3,i4;source-code-pro:n4.js"></script>
<style type="text/css">
        .wf-loading h1, .wf-loading h2, .wf-loading h3, .wf-loading h4,
        .wf-loading h5, .wf-loading h6, .wf-loading p, .wf-loading a {
            visibility: hidden;
        }
    </style>``` in the &lt;head&gt; of your HTML, not at the bottom. (Font weights 300, 400 and 600 are included in that snippet.)

If you feel like hosting the font yourself you can get the fonts here: https://github.com/adobe-fonts/source-sans-pro

Thanks @dnbard!

**Comment by dnbard** [comment]
@larz0  done. Is this what are you were asking for?

**Comment by larz0** [comment]
Let me know if you need more help 👍

**Comment by dnbard** [comment]
Done. Will be available in production in several hours.

**Comment by larz0** [comment]
Thanks, I'll close this.
