### ISSUE TITLE
Upcoming Lodash 3.x Update

### ISSUE THREAD

**Issue by MarcelGerber** [dnbard/brackets-extension-rating#111]
Dear Brackets extension developer,
we're planning to update the version of [Lodash](https://lodash.com) used in Brackets to 3.x (currently, we use 2.4.1).
As we've had a look at your extension, we noticed there's some code that may cause issues while migrating. Thus, we suggest to update your extension so the migration can happen frictionless.
For your extension, we've identified this issue:
Multiple places: `_.template` with more than 1 parameter won't be supported any more. Instead, use the [new syntax](https://lodash.com/docs#template) `_.template(string)(data)`

Further information:
[Lodash compatibility warnings](https://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings)
[Brackets issue about updating Lodash](https://github.com/adobe/brackets/issues/10550)

**Comment by dnbard** [comment]
Thanks! Any estimate when Brackets will start using the new Lodash ?

**Comment by MarcelGerber** [comment]
A, forgot to say that: The solution I suggested works in _both_ Lodash 2.4.1 and Lodash 3.x, so you can safely do the transition now.

**Comment by MarcelGerber** [comment]
@dnbard Did you already have a look at the transition suggested here?

**Comment by dnbard** [comment]
@MarcelGerber  Yes, everything is should be fine now.
