### ISSUE TITLE
[ANTIVIRUS] Antivirus sees tracking domain as malicious?

### ISSUE THREAD

**Issue by mirorauhala** [dnbard/brackets-extension-rating#119]
So I really like this extension, but I wonder why Malwarebytes would think the DOMAIN is bad in any way.

![malwarebytes](https://cloud.githubusercontent.com/assets/4082806/11428899/68d8d508-9479-11e5-8e07-43a111ae2bdd.png)

After quickly looking up information about the rhcloud.com domain from VirusTotal.com, I found out that only one (out of 66) warns about rhcloud domain.

Is there any malicious content delivered via rhcloud.com or maybe something like a Tor exit-node which would be a possibility for getting labeled as malicious?

**Comment by dnbard** [comment]
1. `rhcloud.com` is an cloud hosting by OpenShift. Maybe some websites that are hosted there aren't good one.
2. I'm going to deprecate `online-dnbard.rhcloud.com` usage in the next version of this extension. Just give me some time to update the source code.

**Comment by mirorauhala** [comment]
Ok great :+1:

**Comment by CentrixDE** [comment]
Sadly there is no change in this one. I get the same Information every 5 minutes.
